name: delta
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.6

  platform: ^3.1.0
  # get:
  dio: ^5.0.0
  pretty_dio_logger: ^1.4.0
  # http: # Ensure this is updated to a valid version
  uuid: ^4.5.1
  # http_parser: ^4.0.1
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.6
  flutter_local_notifications: ^19.0.0
  carousel_slider_plus: ^7.0.0
  url_launcher: ^6.3.1
  path_provider_android: ^2.2.16
  sqflite: ^2.4.0
  intro_slider: ^3.0.2
  file_picker: ^10.0.0
  fluttertoast: ^8.2.12
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0

  cloud_firestore_web: any
  firebase_analytics_web: any
  firebase_auth_web: any
  firebase_core_web: any
  firebase_messaging_web: any
  shared_preferences_web: any
  url_launcher_web: any
  # flutter_web_plugins: any

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter_launcher_icons: "^0.9.0"
  flutter_native_splash: ^2.4.2
  change_app_package_name: ^1.4.0


flutter_app_name:
  name: "دلتا"

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/

  
  fonts:
    - family: GE SS Two
      fonts:
#        - asset: assets/font/ArbFONTS-GE_SS_Two_Bold_4.otf
#        - asset: assets/font/ArbFONTS-GE_SS_TWO_MEDIUM_5.otf
#        - asset: assets/font/ArbFONTS-GE-SS-Two-Light_28.otf
#        - asset: assets/font/GE_SS_Two_Bold.otf
        - asset: assets/font/Cairo-Black.ttf
        - asset: assets/font/Cairo-Bold.ttf
        - asset: assets/font/Cairo-ExtraLight.ttf
        - asset: assets/font/Cairo-Light.ttf
        - asset: assets/font/Cairo-Regular.ttf
        - asset: assets/font/Cairo-SemiBold.ttf
